### ISSUE TITLE
items are not properly aligned

### ISSUE THREAD

**Issue by RedJocker** [RedJocker/OrdersMenu#9]
> For a more beautiful and harmonious look, I would place the names of the dishes on the left side, and the buttons on the right side.
>
> _on revision by [@Razotron ](https://github.com/RazoTRON)_

**Comment by RedJocker** [comment]
It is true that having better alignment improves the UI, but I was thinking it would be an undesired complication if to achieve this one would need a more complex layout scheme of rows and cols. 
Maybe I'm wrong and there is an dumb-easy solution to better align items, but if that is not the case then I'm inclined keep it without concerning with alignment for simplification reasons. 
Users can learn and develop that skill with other more challenging projects.

**Comment by RazoTRON** [comment]
You just need an Arrangement.SpaceBetween argument for the Row composable and put buttons to the separate composable or inside another Row. Here is an example: https://github.com/RedJocker/OrdersMenu/issues/8

**Comment by RedJocker** [comment]
https://github.com/RedJocker/OrdersMenu/issues/8#issuecomment-1442584677
